.model small
.stack
.code
start:
    mov ah,02h
    mov dl,4eh
    int 21h    ; 'N'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,6dh
    int 21h    ; 'm'
    mov dl,65h
    int 21h    ; 'e'
    mov dl,3ah
    int 21h    ; ':'
    mov dl,20h
    int 21h    ; space
    mov dl,4ah
    int 21h    ; 'J'
    mov dl,65h
    int 21h    ; 'e'
    mov dl,72h
    int 21h    ; 'r'
    mov dl,69h
    int 21h    ; 'i'
    mov dl,63h
    int 21h    ; 'c'
    mov dl,68h
    int 21h    ; 'h'
    mov dl,6fh
    int 21h    ; 'o'
    mov dl,20h
    int 21h    ; space
    mov dl,4dh
    int 21h    ; 'M'
    mov dl,2eh
    int 21h    ; '.'
    mov dl,20h
    int 21h    ; space
    mov dl,46h
    int 21h    ; 'F'
    mov dl,72h
    int 21h    ; 'r'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,6eh
    int 21h    ; 'n'
    mov dl,63h
    int 21h    ; 'c'
    mov dl,69h
    int 21h    ; 'i'
    mov dl,73h
    int 21h    ; 's'
    mov dl,63h
    int 21h    ; 'c'
    mov dl,6fh
    int 21h    ; 'o'
    mov dl,0dh
    int 21h    ; carriage return
    mov dl,0ah
    int 21h    ; line feed
    mov dl,42h
    int 21h    ; 'B'
    mov dl,69h
    int 21h    ; 'i'
    mov dl,72h
    int 21h    ; 'r'
    mov dl,74h
    int 21h    ; 't'
    mov dl,68h
    int 21h    ; 'h'
    mov dl,20h
    int 21h    ; space
    mov dl,44h
    int 21h    ; 'D'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,74h
    int 21h    ; 't'
    mov dl,65h
    int 21h    ; 'e'
    mov dl,3ah
    int 21h    ; ':'
    mov dl,20h
    int 21h    ; space
    mov dl,44h
    int 21h    ; 'D'
    mov dl,65h
    int 21h    ; 'e'
    mov dl,63h
    int 21h    ; 'c'
    mov dl,65h
    int 21h    ; 'e'
    mov dl,6dh
    int 21h    ; 'm'
    mov dl,62h
    int 21h    ; 'b'
    mov dl,65h
    int 21h    ; 'e'
    mov dl,72h
    int 21h    ; 'r'
    mov dl,20h
    int 21h    ; space
    mov dl,31h
    int 21h    ; '1'
    mov dl,36h
    int 21h    ; '6'
    mov dl,2ch
    int 21h    ; ','
    mov dl,20h
    int 21h    ; space
    mov dl,32h
    int 21h    ; '2'
    mov dl,30h
    int 21h    ; '0'
    mov dl,30h
    int 21h    ; '0'
    mov dl,34h
    int 21h    ; '4'
    mov dl,0dh
    int 21h    ; carriage return
    mov dl,0ah
    int 21h    ; line feed
    mov dl,65h
    int 21h    ; 'e'
    mov dl,2dh
    int 21h    ; '-'
    mov dl,6dh
    int 21h    ; 'm'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,69h
    int 21h    ; 'i'
    mov dl,6ch
    int 21h    ; 'l'
    mov dl,20h
    int 21h    ; space
    mov dl,61h
    int 21h    ; 'a'
    mov dl,64h
    int 21h    ; 'd'
    mov dl,64h
    int 21h    ; 'd'
    mov dl,72h
    int 21h    ; 'r'
    mov dl,65h
    int 21h    ; 'e'
    mov dl,73h
    int 21h    ; 's'
    mov dl,73h
    int 21h    ; 's'
    mov dl,3ah
    int 21h    ; ':'
    mov dl,20h
    int 21h    ; space
    mov dl,6ah
    int 21h    ; 'j'
    mov dl,65h
    int 21h    ; 'e'
    mov dl,72h
    int 21h    ; 'r'
    mov dl,69h
    int 21h    ; 'i'
    mov dl,63h
    int 21h    ; 'c'
    mov dl,68h
    int 21h    ; 'h'
    mov dl,6fh
    int 21h    ; 'o'
    mov dl,6dh
    int 21h    ; 'm'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,62h
    int 21h    ; 'b'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,6eh
    int 21h    ; 'n'
    mov dl,65h
    int 21h    ; 'e'
    mov dl,73h
    int 21h    ; 's'
    mov dl,66h
    int 21h    ; 'f'
    mov dl,72h
    int 21h    ; 'r'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,6eh
    int 21h    ; 'n'
    mov dl,63h
    int 21h    ; 'c'
    mov dl,69h
    int 21h    ; 'i'
    mov dl,73h
    int 21h    ; 's'
    mov dl,63h
    int 21h    ; 'c'
    mov dl,6fh
    int 21h    ; 'o'
    mov dl,40h
    int 21h    ; '@'
    mov dl,67h
    int 21h    ; 'g'
    mov dl,6dh
    int 21h    ; 'm'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,69h
    int 21h    ; 'i'
    mov dl,6ch
    int 21h    ; 'l'
    mov dl,2eh
    int 21h    ; '.'
    mov dl,63h
    int 21h    ; 'c'
    mov dl,6fh
    int 21h    ; 'o'
    mov dl,6dh
    int 21h    ; 'm'
    mov dl,0dh
    int 21h    ; carriage return
    mov dl,0ah
    int 21h    ; line feed
    mov dl,41h
    int 21h    ; 'A'
    mov dl,64h
    int 21h    ; 'd'
    mov dl,64h
    int 21h    ; 'd'
    mov dl,72h
    int 21h    ; 'r'
    mov dl,65h
    int 21h    ; 'e'
    mov dl,73h
    int 21h    ; 's'
    mov dl,73h
    int 21h    ; 's'
    mov dl,3ah
    int 21h    ; ':'
    mov dl,20h
    int 21h    ; space
    mov dl,53h
    int 21h    ; 'S'
    mov dl,69h
    int 21h    ; 'i'
    mov dl,6ch
    int 21h    ; 'l'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,6eh
    int 21h    ; 'n'
    mov dl,67h
    int 21h    ; 'g'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,6eh
    int 21h    ; 'n'
    mov dl,20h
    int 21h    ; space
    mov dl,49h
    int 21h    ; 'I'
    mov dl,6ch
    int 21h    ; 'l'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,79h
    int 21h    ; 'y'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,2ch
    int 21h    ; ','
    mov dl,20h
    int 21h    ; space
    mov dl,44h
    int 21h    ; 'D'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,72h
    int 21h    ; 'r'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,73h
    int 21h    ; 's'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,2ch
    int 21h    ; ','
    mov dl,20h
    int 21h    ; space
    mov dl,54h
    int 21h    ; 'T'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,6eh
    int 21h    ; 'n'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,75h
    int 21h    ; 'u'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,6eh
    int 21h    ; 'n'
    mov dl,20h
    int 21h    ; space
    mov dl,43h
    int 21h    ; 'C'
    mov dl,69h
    int 21h    ; 'i'
    mov dl,74h
    int 21h    ; 't'
    mov dl,79h
    int 21h    ; 'y'
    mov dl,0dh
    int 21h    ; carriage return
    mov dl,0ah
    int 21h    ; line feed
    mov dl,50h
    int 21h    ; 'P'
    mov dl,72h
    int 21h    ; 'r'
    mov dl,6fh
    int 21h    ; 'o'
    mov dl,76h
    int 21h    ; 'v'
    mov dl,69h
    int 21h    ; 'i'
    mov dl,6eh
    int 21h    ; 'n'
    mov dl,63h
    int 21h    ; 'c'
    mov dl,65h
    int 21h    ; 'e'
    mov dl,3ah
    int 21h    ; ':'
    mov dl,20h
    int 21h    ; space
    mov dl,42h
    int 21h    ; 'B'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,74h
    int 21h    ; 't'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,6eh
    int 21h    ; 'n'
    mov dl,67h
    int 21h    ; 'g'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,73h
    int 21h    ; 's'
    mov dl,0dh
    int 21h    ; carriage return
    mov dl,0ah
    int 21h    ; line feed
    mov dl,43h
    int 21h    ; 'C'
    mov dl,6fh
    int 21h    ; 'o'
    mov dl,6eh
    int 21h    ; 'n'
    mov dl,74h
    int 21h    ; 't'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,63h
    int 21h    ; 'c'
    mov dl,74h
    int 21h    ; 't'
    mov dl,20h
    int 21h    ; space
    mov dl,4eh
    int 21h    ; 'N'
    mov dl,75h
    int 21h    ; 'u'
    mov dl,6dh
    int 21h    ; 'm'
    mov dl,62h
    int 21h    ; 'b'
    mov dl,65h
    int 21h    ; 'e'
    mov dl,72h
    int 21h    ; 'r'
    mov dl,3ah
    int 21h    ; ':'
    mov dl,20h
    int 21h    ; space
    mov dl,30h
    int 21h    ; '0'
    mov dl,39h
    int 21h    ; '9'
    mov dl,39h
    int 21h    ; '9'
    mov dl,34h
    int 21h    ; '4'
    mov dl,31h
    int 21h    ; '1'
    mov dl,32h
    int 21h    ; '2'
    mov dl,35h
    int 21h    ; '5'
    mov dl,37h
    int 21h    ; '7'
    mov dl,31h
    int 21h    ; '1'
    mov dl,31h
    int 21h    ; '1'
    mov dl,32h
    int 21h    ; '2'
    mov dl,0dh
    int 21h    ; carriage return
    mov dl,0ah
    int 21h    ; line feed
    mov dl,47h
    int 21h    ; 'G'
    mov dl,75h
    int 21h    ; 'u'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,72h
    int 21h    ; 'r'
    mov dl,64h
    int 21h    ; 'd'
    mov dl,69h
    int 21h    ; 'i'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,6eh
    int 21h    ; 'n'
    mov dl,27h
    int 21h    ; apostrophe
    mov dl,73h
    int 21h    ; 's'
    mov dl,20h
    int 21h    ; space
    mov dl,4eh
    int 21h    ; 'N'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,6dh
    int 21h    ; 'm'
    mov dl,65h
    int 21h    ; 'e'
    mov dl,3ah
    int 21h    ; ':'
    mov dl,20h
    int 21h    ; space
    mov dl,47h
    int 21h    ; 'G'
    mov dl,69h
    int 21h    ; 'i'
    mov dl,72h
    int 21h    ; 'r'
    mov dl,6ch
    int 21h    ; 'l'
    mov dl,69h
    int 21h    ; 'i'
    mov dl,65h
    int 21h    ; 'e'
    mov dl,20h
    int 21h    ; space
    mov dl,4dh
    int 21h    ; 'M'
    mov dl,2eh
    int 21h    ; '.'
    mov dl,20h
    int 21h    ; space
    mov dl,46h
    int 21h    ; 'F'
    mov dl,72h
    int 21h    ; 'r'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,6eh
    int 21h    ; 'n'
    mov dl,63h
    int 21h    ; 'c'
    mov dl,69h
    int 21h    ; 'i'
    mov dl,73h
    int 21h    ; 's'
    mov dl,63h
    int 21h    ; 'c'
    mov dl,6fh
    int 21h    ; 'o'
    mov dl,0dh
    int 21h    ; carriage return
    mov dl,0ah
    int 21h    ; line feed
    mov dl,4fh
    int 21h    ; 'O'
    mov dl,63h
    int 21h    ; 'c'
    mov dl,63h
    int 21h    ; 'c'
    mov dl,75h
    int 21h    ; 'u'
    mov dl,70h
    int 21h    ; 'p'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,74h
    int 21h    ; 't'
    mov dl,69h
    int 21h    ; 'i'
    mov dl,6fh
    int 21h    ; 'o'
    mov dl,6eh
    int 21h    ; 'n'
    mov dl,3ah
    int 21h    ; ':'
    mov dl,20h
    int 21h    ; space
    mov dl,41h
    int 21h    ; 'A'
    mov dl,73h
    int 21h    ; 's'
    mov dl,73h
    int 21h    ; 's'
    mov dl,69h
    int 21h    ; 'i'
    mov dl,73h
    int 21h    ; 's'
    mov dl,74h
    int 21h    ; 't'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,6eh
    int 21h    ; 'n'
    mov dl,74h
    int 21h    ; 't'
    mov dl,20h
    int 21h    ; space
    mov dl,4ch
    int 21h    ; 'L'
    mov dl,65h
    int 21h    ; 'e'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,64h
    int 21h    ; 'd'
    mov dl,65h
    int 21h    ; 'e'
    mov dl,72h
    int 21h    ; 'r'
    mov dl,20h
    int 21h    ; space
    mov dl,2fh
    int 21h    ; '/'
    mov dl,20h
    int 21h    ; space
    mov dl,46h
    int 21h    ; 'F'
    mov dl,61h
    int 21h    ; 'a'
    mov dl,63h
    int 21h    ; 'c'
    mov dl,74h
    int 21h    ; 't'
    mov dl,6fh
    int 21h    ; 'o'
    mov dl,72h
    int 21h    ; 'r'
    mov dl,79h
    int 21h    ; 'y'
    mov dl,20h
    int 21h    ; space
    mov dl,57h
    int 21h    ; 'W'
    mov dl,6fh
    int 21h    ; 'o'
    mov dl,72h
    int 21h    ; 'r'
    mov dl,6bh
    int 21h    ; 'k'
    mov dl,65h
    int 21h    ; 'e'
    mov dl,72h
    int 21h    ; 'r'
    mov dl,0dh
    int 21h    ; carriage return
    mov dl,0ah
    int 21h    ; line feed
    mov ah,4ch
    int 21h
end start